gitlab-ci-pipelines-exporter: add namespace for ClusterRoleBinding
ClusterRoleBindings require namespaced subjects.

Error: ClusterRoleBinding.rbac.authorization.k8s.io "gitlab-metrics" is invalid: subjects[0].namespace: Required value