Updates to gitlab-ci-pipelines-exporter (#67)
* gitlab-ci-pipelines-exporter: add namespace for ClusterRoleBinding

ClusterRoleBindings require namespaced subjects.

Error: ClusterRoleBinding.rbac.authorization.k8s.io "gitlab-metrics" is invalid: subjects[0].namespace: Required value

* Chart.yaml: update redis dependency to 16.13.2

Previous chart version no longer supported.